name: sample-golang-notes
services:
- name: web
  github:
    repo: digitalocean/sample-golang-notes
    branch: main
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
databases:
- name: db
  engine: PG
  version: "12"
